# Generated by Django 5.2.1 on 2025-07-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_app.tasklist'),
            preserve_default=False,
        ),
    ]
