# Generated by Django 5.2.1 on 2025-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0003_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
