# Generated by Django 5.2.1 on 2025-07-26 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0006_tasklist_user_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 8, 29, 54, 700380, tzinfo=datetime.timezone.utc)),
        ),
    ]
